<a href="https://colab.research.google.com/github/M-Coh/M-Coh/blob/main/Assignments/Assignment01-Basics/CohMatija_Assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[<img align="right" width="200" height="200" src="https://www.tu-braunschweig.de/typo3conf/ext/tu_braunschweig/Resources/Public/Images/Logos/tu_braunschweig_logo.svg">](https://www.tu-braunschweig.de/en/)

[Mehdi Maboudi](https://www.tu-braunschweig.de/en/igp/staff/mehdi-maboudi) ([m.maboudi@tu-bs.de](m.maboudi@tu-bs.de))

[Technical University of Braunschweig](https://www.tu-braunschweig.de/en/)  
[Institute of Geodesy and Photogrammetry](https://www.tu-braunschweig.de/igp)  
***

Considering _Tom Mitchell_ definition:  
A computer program is said to learn from experience 𝐸 with respect to some task T and some
performance measure 𝑃, if its performance on 𝑇, as measured by 𝑃, improves with experience 𝐸

<font color='red'>## E1 (12 pnt)</font>

Select 4 machine learning applications and answer the following questions:
- **Task(T)**
- **Experience(E)**
- **Measure Performance(P)**
***

**Example from the lecture:**

**Applications**: Spam filtering
  
- **Task(T)**: The task is to learn how to classify emails as spam or ham(non-spam).
- **Experience(E)**: The dataset is a set consisting of emails and their labels (spam or ham).
- **Measure Performance(P)**: count the number of correct predictions to asses the prediction accuracy.

_**Category**_. Since we are looking for 2 class labels (spam, non-spam), this is a supervised binary classification.
***

**Applications01**: Image Recognition of different animals
  
- **Task(T)**: The task is to classify images into different categories (for example cathegories of different animals: cats, dogs, rabbits...)
- **Experience(E)**: A dataset of labeled images where each image is tagged with the correct category.
- **Measure Performance(P)**: Accuracy, which is the percentage of correctly classified images.

_**Category**_. Supervised multi-class classification.
***

**Applications02**: Student Grade Prediction Based on Related Course Grades
  
- **Task(T)**: To predict a student's grade in a specific course based on their performance in other related courses.
- **Experience(E)**: Academic records showing students' grades in multiple courses, where the relationship between course performances can be learned.
- **Measure Performance(P)**: Error between predicted and actual grades

_**Category**_. Supervised regression (for numerical grade prediction, for example from 0 to 100)
***

**Applications03**: House Price Prediction
  
- **Task(T)**: To predict the selling price of a house based on its features (size, location, number of rooms...)
- **Experience(E)**: Data of house sales including features like size, location, number of rooms and their sale prices.
- **Measure Performance(P)**: Error between predicted and actual prices

_**Category**_. Supervised regression
***

**Applications04**: Segmenting clients based on purchase behavior for targeted marketing
  
- **Task(T)**: Segmenting clients based on their purchases so that you can design a different marketing strategy
for each segment.
- **Experience(E)**: purchase data and categories of products.
- **Measure Performance(P)**: metrics that measure
compactness (how close points within the same cluster are to each other).

_**Category**_. Unsupervised clustering
***

<font color='red'>## E2 (20 pnt)</font>

Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual features do not more or less look like standard normally distributed data (e.g. Gaussian with 0 mean and unit variance).  
In this Exercise we will write a very simplified and naive feature normalizer

Given the function below called `normalizer` do the following step:
 - **ducumentation** (4pnts)
 - **function implementation** (12pnts)  
      Normalizing the elements of a 2D array:
    
            For each element of a column:
            Subtract the mean and devide it by variance (this is called Centering and scaling)

            Considering "i"th element of "j"th column of array X as x[i,j],
            transforme x[i,j] to z[i,j]:

            z[i,j] = (x[i,j] - u) / s

            where u is the mean of the column j and s is the standard deviation of that column.
 - **test your function** (4pnts). Do not forget edge cases
      
You can get some hints from folowing link:   
**But do not use it directly and write your code just with low level numpy and python commands**  
[sklearn.preprocessing.StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [ ]:
def normalizer(X):
    """
    Documentation:
        function description: This function standardizes (normalizes) a 2D numpy array by transforming each column
        so that it has mean = 0 and standard deviation = 1.
        The transformation is performed column-wise:
            z[i,j] = (x[i,j] - mean_j) / std_j,
        for every column j of the input array x ve calculate the mean and standard deviation of column j and
        apply the transformation to the entire column.

        inputs: A 2D NumPy array of shape (n_samples, n_features) containing numerical data.
        Each row represents one sample.
        Each column represents one feature (variable) that will be standardized.
        The array must contain only numeric values.
        outputs: A 2D NumPy array of the same shape as X.
        Each column of X_transformed has been standardized to have:
        mean = 0 and standard deviation = 1
        The output contains the normalized version of the input data.
    """
    ### Start of your code ##

    # check the inputs
    if not isinstance(X, np.ndarray):
        raise TypeError("Input X must be a numpy array")
    if X.ndim != 2:
        raise ValueError("Input X must be a 2D array")
    if not np.issubdtype(X.dtype, np.number):
        raise TypeError("All elements in X must be numeric (int or float)")
    # main body
    X_transformed = X.copy().astype(float)  #to avoid modifying original

    n_samples, n_features = X.shape #number of rows and columns

    for j in range(n_features):
        col = X[:, j]
        mean = np.mean(col)
        std = np.std(col)

        # avoid division by zero if std = 0
        if std == 0:
            X_transformed[:, j] = 0
        else:
            X_transformed[:, j] = (col - mean) / std
    ### End of your code ##

    return X_transformed

Add your tests in separate cells

In [ ]:
import numpy as np

# --- Test 1: normal example ---
X1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=float)

Z1 = normalizer(X1)
print("Test 1 - Original:\n", X1)
print("Test 1 - Normalized:\n", Z1)
print("Column means:", np.mean(Z1, axis=0))  # ~0
print("Column stds:", np.std(Z1, axis=0))    # ~1

Test 1 - Original:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Test 1 - Normalized:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
Column means: [0. 0. 0.]
Column stds: [1. 1. 1.]


In [ ]:
# --- Test 2: edge case - column with all identical values ---
X2 = np.array([
    [5, 1],
    [5, 2],
    [5, 3]
], dtype=float)

Z2 = normalizer(X2)
print("\nTest 2 - Edge case (constant column):\n", Z2)
# First column is constant -> all values become 0
# Second column is normalized normally


Test 2 - Edge case (constant column):
 [[ 0.         -1.22474487]
 [ 0.          0.        ]
 [ 0.          1.22474487]]


<font color='red'>## E3 (30 pnt)</font>  
Transform features by scaling each feature to a given range.

Write a function to transform features by scaling each feature to a given range.

- Understanding the problem(10)  
- Documentation (4pnts)  
- Function implementation (12pnts)  
- Test your function (4pnts)
- selecting proper name for function and variables (3pnts)

You should check the following link to understand the problem:  
**But do not use it directly and write your code just with low level numpy and python commands**  
[sklearn.preprocessing.MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)

In [ ]:
import numpy as np

def min_max_scaler(X, feature_range=(0, 1)):
    """
    Documentation:
        Function description: This function scales each feature (column) of a 2D numpy array to a given range.
        The transformation is performed column-wise:
            x_scaled[i,j] = (x[i,j] - min_j) / (max_j - min_j) * (max_range - min_range) + min_range
        where min_j and max_j are the minimum and maximum values of column j, and
        min_range and max_range define the desired output range.

        Inputs:
            X : A 2D NumPy array of shape (n_samples, n_features) containing numerical data.
                Each row represents one sample.
                Each column represents one feature (variable) to be scaled.
                The array must contain only numeric values.
            feature_range : interval (min_range, max_range), the desired range of transformed data.
                Default is (0, 1).

        Outputs:
            X_scaled : A 2D NumPy array of the same shape as X.
                Each column has been scaled to the specified range (interval).
    """
    ### Start of your code ###

    # --- check inputs ---
    if not isinstance(X, np.ndarray):
        raise TypeError("Input X must be a numpy array")
    if X.ndim != 2:
        raise ValueError("Input X must be a 2D array")
    if not np.issubdtype(X.dtype, np.number):
        raise TypeError("All elements in X must be numeric (int or float)")
    if not isinstance(feature_range, tuple) or len(feature_range) != 2:
        raise ValueError("feature_range must be a tuple of length 2")

    min_range, max_range = feature_range
    if min_range >= max_range:
        raise ValueError("feature_range[0] must be smaller than feature_range[1]")

    # --- main body ---
    X_scaled = X.copy().astype(float)  # avoid modifying original
    n_samples, n_features = X.shape

    for j in range(n_features):
        col = X[:, j]
        col_min = np.min(col)
        col_max = np.max(col)
        # avoid division by zero if col_min == col_max
        if col_max == col_min:
            # set to middle of range (avg) if all values are identical
            X_scaled[:, j] = (min_range + max_range) / 2
        else:
            X_scaled[:, j] = (col - col_min) / (col_max - col_min) * (max_range - min_range) + min_range

    ### End of your code ###
    return X_scaled


In [ ]:
# Test 1: basic example
X1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=float)
Z1 = min_max_scaler(X1, feature_range=(0, 1))
print("Test 1 - Scaled:\n", Z1)

# Test 2: edge case - constant column
X2 = np.array([
    [5, 1],
    [5, 2],
    [5, 3]
], dtype=float)
Z2 = min_max_scaler(X2, feature_range=(-1, 1))
print("\nTest 2 - Edge case (constant column):\n", Z2)

Test 1 - Scaled:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

Test 2 - Edge case (constant column):
 [[ 0. -1.]
 [ 0.  0.]
 [ 0.  1.]]
